name 'ruby_rbenv_download'
maintainer 'Jonathan Serafini'
maintainer_email 'jonathan@serafini.ca'
license 'apache2'
description 'Installs/Configures ruby_rbenv_download'
long_description 'Installs/Configures ruby_rbenv_download'
version '0.1.0'
depends 'ruby_rbenv', '~> 1.0.0'
