name 'ruby_rbenv_download'
maintainer 'Jonathan Serafini'
maintainer_email 'jonathan@serafini.ca'
source_url 'https://github.com/JonathanSerafini/chef-ruby_rbenv_download'
issues_url 'https://github.com/JonathanSerafini/chef-ruby_rbenv_download/issues'
license 'apache2'
description 'Provides ruby_rbenv_download to download ruby from binaries'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
chef_verison '>= 12.7'
version '0.1.0'
depends 'ruby_rbenv', '~> 1.0.0'
